name: fitquest
description: FitQuest - your fitness journey awaits
publish_to: "none"

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter

  provider: ^6.1.2
  firebase_core: ^3.8.0
  firebase_auth: ^5.1.3
  cloud_firestore: ^5.4.4
  google_maps_flutter: ^2.7.1
  geolocator: ^10.1.0
  sqflite: ^2.4.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  
  # Make sure indentation is exactly 2 spaces
  assets:
    - assets/Image.jpg