// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDYkxr_w56bhIxfPbVnUo6_N5HvuFvjP7k',
    appId: '1:1001969982574:web:7e83bb785b6ce503f79a7f',
    messagingSenderId: '1001969982574',
    projectId: 'fitquest-mobile-project',
    authDomain: 'fitquest-mobile-project.firebaseapp.com',
    storageBucket: 'fitquest-mobile-project.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCwR5ys5HyuxM91XPQ1F4EWeYJ3X7Th6xw',
    appId: '1:1001969982574:android:0166a9465033a151f79a7f',
    messagingSenderId: '1001969982574',
    projectId: 'fitquest-mobile-project',
    storageBucket: 'fitquest-mobile-project.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAcrzfDokBIYPk1mwlvYGAwcuj5OS5ogLM',
    appId: '1:1001969982574:ios:c12c77ea6aba91b5f79a7f',
    messagingSenderId: '1001969982574',
    projectId: 'fitquest-mobile-project',
    storageBucket: 'fitquest-mobile-project.firebasestorage.app',
    iosBundleId: 'com.example.mobileProjectFitquest',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAcrzfDokBIYPk1mwlvYGAwcuj5OS5ogLM',
    appId: '1:1001969982574:ios:c12c77ea6aba91b5f79a7f',
    messagingSenderId: '1001969982574',
    projectId: 'fitquest-mobile-project',
    storageBucket: 'fitquest-mobile-project.firebasestorage.app',
    iosBundleId: 'com.example.mobileProjectFitquest',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDYkxr_w56bhIxfPbVnUo6_N5HvuFvjP7k',
    appId: '1:1001969982574:web:73c21d71d07a2d90f79a7f',
    messagingSenderId: '1001969982574',
    projectId: 'fitquest-mobile-project',
    authDomain: 'fitquest-mobile-project.firebaseapp.com',
    storageBucket: 'fitquest-mobile-project.firebasestorage.app',
  );
}
